# Generated by Django 5.0.6 on 2024-06-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_year", models.CharField(blank=True, max_length=4, null=True)),
                ("intensity", models.IntegerField()),
                ("sector", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=255)),
                ("insight", models.TextField()),
                ("url", models.URLField()),
                ("region", models.CharField(max_length=255)),
                ("start_year", models.CharField(blank=True, max_length=4, null=True)),
                ("impact", models.CharField(blank=True, max_length=255, null=True)),
                ("added", models.DateTimeField()),
                ("published", models.DateTimeField()),
                ("country", models.CharField(max_length=255)),
                ("relevance", models.IntegerField()),
                ("pestle", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                ("title", models.TextField()),
                ("likelihood", models.IntegerField()),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
