# Generated by Django 5.0.6 on 2024-06-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datapoint",
            name="added",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="impact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="insight",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="pestle",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="published",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="sector",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="topic",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
